server:
  name: backend-service
  port: :8088
  read_timeout: 10
  write_timeout: 5
  token_expiration: 24
  dry_run: false

database:
  driver: mysql
  address: 127.0.0.1:3306
  default_db: cronspy
  username: root
  password: robert
  max_open_connections: 5
  max_idle_connections: 1
  max_lifetime: 300